apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-resource-group
  namespace: azure
  title: Azure Resource Group
  label: resourceGroup
  description: Criação de Resource Group no Azure
  tags: [azure, terraform, iac, resource-group]
  #annotations:
  #  backstag.io/addon-of: 
  #hidden: true
  links:
    - url: https://github.com/leandromoreirati/tf-module-azure-resource-group
      title: GitHub Repo
      icon: github
spec:
  #owner: infrastructure/devops
  type: Infrastructure
  parameters:
    - title: Configurações do Resource Group
      required: [name, location]
      properties:
        name:
          title: 'Name'
          type: string
          description: 'Nome do `Resource Group`'
          default: 'my-rg'
          maxLength: 63
          pattern: '^[a-zA-Z0-9\-]*$'
          ui:autofocus: true
          ui:help: 'Máximo de 63 caracteres. Permite letras, números e traço.'
        location:
          title: 'Location'
          type: string
          description: 'Location do `Resource Group`'
          maxLength: 100
          default: 'useast2'
          #ui:autofocus: true
          ui:help: 'Região on de o Resource Group será criado.'
        owner:
          title:  Proprietário(s)
          type: string
          description: Equipe Responsável pelo projeto
          iu:field: OwnerPicker
          ui:options:
            allowedKinds: [Group]
    #- title: 'Repositório da Infraestrutura'
    #  required: [repoUrl]
    #  properties:
    #    repoUrl:
    #      title: Repository
    #      type: string
    #      ui:field: RepoUrlPicker
    #      ui:options:
    #        allowedHosts:
    #          - github.com
    #        allowedOwners:
    #          - leandromoreirati
    
    - title: 'Repositório da Infraestrutura'
      required: [repoUrl]
      properties:
        repoUrl:
          title: Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com
  steps:
    #- id: infos
    #  name: Carregando Informações
    #  action: catalog:fetch
    #  input:
    #    entityRef: ${{ parameters.name }}
#
    #- id: debug:fetch
    #  name: Debug Fetchers
    #  action: debug:log
    #  input:
    #    infos: ${{ stepinfos.output }}
#
    #- id: debug:field
    #  name: Debug Field
    #  action:  debug:log
    #  input:
    #    parameters: ${{ parameters }}

    - id: fetch-base
      name: Aplicando template (Azure Resource Group)
      action: fetch:template
      input:
        #targetPath: aws-lambda/${{ parameters.name }}/
        #url: https://github.com/leandromoreirati/tf-module-azure-resource-group
        url: ./skeleton
        targetPath: ./
        replace: true
        #copyWithoutTemplating:
        #  - "**/*.full"
        values:
          name: ${{ parameters.name }}
          location: ${{ parameters.location }}
          #tag: ${{ parameters.tag }}
          owner: ${{ parameters.owner }}

    - id: fetch-model
      name: Fecth Template
      action: fetch:plain
      input:
        url: https://github.com/leandromoreirati/tf-module-azure-resource-group
        targetPath: ./

    #- id: publish
    #  name: Publish
    #  action: publish:github
    #  input:
    #    allowedHosts: ['github.com']
    #    description: This is ${{ parameters.name }}
    #    repoUrl: ${{ parameters.repoUrl }}
    #    repoVisibility: public # or 'internal' or 'private'
    #    defaultBranch: main
    #    protectDefaultBranch: true
    #    deleteBranchOnMerge: true
    #    #gitCommitMessage: "Commit by Internal Developer Portal(IDP)."


    - id: publish_azure
      action: publish:azure
      name: Publish to Azure
      input:
        #repoUrl: dev.azure.com?organization=organization&owner=project&repo=repo # dev.azure.com?owner=leandromoreirati&repo=my-rg&organization=IaCautomacao
        #description: Initialize a git repository
        #defaultBranch: main
        #allowedHosts: ['dev.azure.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        token: bkd3u656lvjj4ldzrtoy2b6psysqnfxqxcvhcj3d5gdglquwdrcq
        defaultBranch: main

    #- id: publish_azure
    #  action: publish:azure
    #  name: Publish to Azure
    #  input:
    #    repoUrl: dev.azure.com?organization=organization&owner=project&repo=repo
    #    description: Initialize a git repository
    #    defaultBranch: main
  
    #- id: register
    #  name: Register
    #  action: catalog:register
    #  input:
    #    repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    #    #repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #    catalogInfoPath: '/catalog-info.yaml'
  
    - id: register_azure
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish_azure'].output.repoContentsUrl }}
        #repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repositório
        #url: ${{steps.publish.output.remoteUrl}}
        url: ${{ steps['publish'].output.remoteUrl }}

      - title: Catalog
        icon: catalog
        #url: ${{steps.register.output.entityRef}}
        #url: ${{ steps['register'].output.entityRef }}
        url: ${{ steps['register_azure'].output.entityRef }}
        #entityRef: ${{ steps['register'].output.entityRef }}