apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-${{ values.name }}
  description: |
    [Azure Resource Group](https://github.com/leandromoreirati/tf-module-azure-resource-group)
    Terraform module to create On Azure Resource Group
  #labels:
  #  example.com/custom: custom_label_value
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/code-coverage: scm-only
    backstage.io/template-origin: template:azure/azure-resource-group
    backstage.io/repo-url: ${{ values.repoUrl }}
  tags:
    - infrastructure
    - iac
    - terraform
  links:
    - url: https://github.com/leandromoreirati/tf-module-azure-resource-group
      title: GitHub Repo
      icon: github
spec:
  type: service
  owner: leandromoreirati
  lifecycle: production
  #dependsOn:
  #  - "${{ values.name }}"